# Generated by Django 3.1.4 on 2020-12-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('desc', models.TextField()),
                ('new_img', models.ImageField(upload_to='images/')),
                ('date', models.DateField()),
            ],
        ),
    ]
