# Generated by Django 3.1.4 on 2021-01-01 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0003_posts_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='date',
        ),
    ]
